version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-stack-name"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-15g6saneuuu7q"
s3_prefix = "sam-stack-name"
region = "us-east-2"
profile = "hyun"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
